# Generated by Django 6.0.6 on 2026-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_file', models.FileField(upload_to='uploads/')),
                ('bank_filename', models.CharField(max_length=255)),
                ('ledger_file', models.FileField(upload_to='uploads/')),
                ('ledger_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count_bank', models.IntegerField(default=0)),
                ('row_count_ledger', models.IntegerField(default=0)),
                ('match_rate', models.FloatField(blank=True, null=True)),
                ('error', models.CharField(blank=True, null=True)),
                ('status', models.CharField(max_length=40)),
                ('results', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
