# ? wtf? this? why need to take care nginx processes or threads?
worker_processes auto;

# ? what does events do?
# ? and worker connections? why 4096? if it is the max limit? but why is ther a max limit at all?
# ? moreover why not straight up 1000000 for max speed?
events {
    worker_connections 4096;
}

# ? does http{} block handles and configures http connection ?
# * http {} doesn't itself "handle an HTTP connection." 
# * It contains the configuration Nginx uses to handle HTTP traffic.
http {
    upstream django {
        # * our django webservice is running at 8000 right
        # * nginx want to know its url
        server web-1:8001;
        server web-2:8001;
        server web-3:8001;
    }

    server {

        # ? Assuming NGINGX willl listen on this server dumbfuck... 
        # * you forget it again right
        listen 80;

        # ? endpoint url for where i will access this microservice, right?
        # * For requests matching /, proxy them to the django upstream.
        location / {
            # ? so this url endpoint will access the upstream django server
            # ? the one you wrote in http
            proxy_pass http://django;
            # ? wtf is this is nginx want to know my host id so it can connect to me?
            # ? why does it need to connect ot me since it is in local host?
            proxy_set_header Host $host;
            # ? same now asking for ip address too i guess...
            # ? though can be something else entirely?
            proxy_set_header X-Real-IP $remote_addr;
            # ? a proxy forwarder for what load balancing or migrating?
            # * This is not for load balancing or migration.
            # * It's primarily for preserving the chain of client/proxy IP addresses.
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # ? proto? schema? some protobuf? or grpc? shit?
            # nah that's too far from what we are doing anyway let me know?
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ? so i guess an endpoint with /static/ right?
        # ? but for what?
        # ? what is alias? i don't even have a static director?
        location /static/ {
            alias /static/;
        }
    }
}